### ISSUE TITLE
Admin json changes

### ISSUE THREAD

**Issue by ryanto** [tedconf/front_end_builds#23]
Hey I made some changes to the admin JSON. I think the front end will need to be updated.

```
GET /frontends-admin/apps'
```

```
app: {
  api_key: "key"
  best_build_id: 15
  build_ids: [15, 14, 13, 12, 11, 10, 9, 8, 7, 6]
  id: 1
  name: "app-name"
}
builds: [
0: {id: 15, app_id: 1, sha: "89729f73945bc748bbfb96af884738e8a1b3e8cc", branch: "master"}
1: {id: 14, app_id: 1, sha: "89729f73945bc748bbfb96af884738e8a1b3e8cc", branch: "master"}
2: {id: 13, app_id: 1, sha: "89729f73945bc748bbfb96af884738e8a1b3e8cc", branch: "master"}
...
]
```

The big changes here are.

1) Builds don't know if they are the best are not. App payload just has a best_build_id which points to the best build.

2) Builds array only has the 10 most recent builds. I figure most apps will very quickly get to hundreds of builds and replying with that much JSON is overkill. If the best build is not in a the builds array then Ember will have to request it from the backend (based on id).

2 cont) Since we only reply with 10 builds I guess we should do some sort of pagination or all so you can see more if you want to. This is pretty easy, but I haven't done it yet... which of these do you like best:

Pagination: 

```
GET /builds?app_id=7&per_page=10&page=3
```

All

```
GET /builds?app_id=7&showAll=true
```

**Comment by samselikoff** [comment]
Shouldn't api calls from admin to backend still be under an `api` namespace? What if we want to add an `apps` route to the ember admin app

**Comment by samselikoff** [comment]
03a4b2d2b500e47097f3ebd36ceac5adab0d40f2 closes.
