### ISSUE TITLE
Store configuration on server

### ISSUE THREAD

**Issue by ryanto** [tedconf/front_end_builds#47]
Right now there is a lot of configuration. Setting up the router, adding apps the UI, adding front ends to the router, configuring cli for deploy, etc.

In order to simplify some of this we will use the UI as the main place for adding and editing configuration. This should eliminate(?) the needs for deploy.js on the cli side as well as provide a central place for configs, making it easy to know where changes get made.

The CLI client will still be responsible for knowing its S3 access keys as well as the location of the FEB server it's deploying to. For FEB server location we can store that in ``config/environment.js``. For S3 keys we can just default to looking at ENV vars, but provide an override hook if the cli tool wants to pull them from elsewhere.

Most of the work for this will be done on the cli side of things, but it starts with the engine holding config.

I think it makes sense to move to ssh key based auth before building this out.

**Comment by samselikoff** [comment]
Sounds great

**Comment by ryanto** [comment]
Since this will, at one point, become an ember-cli-deploy plugin I think we should punt on this. Once that happens we should have a better picture about feb configuration.

**Comment by samselikoff** [comment]
:+1:
