### ISSUE TITLE
Can't activate / deactive builds on Rails 4.2

### ISSUE THREAD

**Issue by hhff** [tedconf/front_end_builds#51]
Hi Guys!

Having trouble getting the activate / deactivate stuff working.  When I hit my builds page, every build is marked as Active, and attempting to deactivate them doesn't work (failed `PUT` request).

Currently testing on Heroku with the github version of this Gem.  (Rails 4.2)

Screencap here:
https://drive.google.com/file/d/0B_A4sox6VN4Mbm4yUVhEMkVyMEk/view?usp=sharing

routes.rb
```ruby
  # Backend
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount FrontEndBuilds::Engine, at: '/builds'
  end

  # API
  namespace :api do
    resources :posts
  end

  # Frontend
  front_end 'my-ember-frontend', '/'
```

Any ideas?  If not - I'm happy to dive into this - just wont have time today.

**Comment by samselikoff** [comment]
Hey @hhff !

We actually are in the middle of reworking this - we used to have a concept of an active/inactive build, but we're moving to having a single `live_build` per app. You'll be able to manually activate builds after we merge [this PR](https://github.com/tedconf/front_end_builds/pull/48) in, which will probably happen in the next day or so.

For now, if you push a new master build (a build whose branch is `'master'`), it should become live.

**Comment by samselikoff** [comment]
(you'll also still be able to visit non-live builds)

**Comment by hhff** [comment]
bam!  nailed it

thankyou!  loving this build process guys
